"""rename comment column for Comment table

Revision ID: 1b4f063a42a2
Revises: edc8b0f83cbf
Create Date: 2017-11-04 19:55:04.011986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4f063a42a2'
down_revision = 'edc8b0f83cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(length=255), nullable=True))
    op.drop_column('comments', 'commnet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('commnet', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
