"""dropped all db tables

Revision ID: 3520b7c7182d
Revises: 60d806a0a47e
Create Date: 2017-11-04 17:45:35.462900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3520b7c7182d'
down_revision = '60d806a0a47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'lines')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('lines', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
