"""added lines column name

Revision ID: 7d58be61d344
Revises: df2d3ab625cd
Create Date: 2017-11-04 18:05:33.245171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d58be61d344'
down_revision = 'df2d3ab625cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('lines', sa.String(length=255), nullable=True))
    op.drop_column('pitches', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'lines')
    # ### end Alembic commands ###
